### ISSUE TITLE
K210 features available or needs development?

### ISSUE THREAD

**Issue by JeffreyUrban** [vowstar/k210-linux-nommu#16]
I'd like to know if the K210's specific features (KPU neural accelerator, etc) are available as built here, or if including support for them is a further exercise. 

Thanks :)

**Comment by vowstar** [comment]
KPU does not seem to be feasible at present because of insufficient physical memory. Currently, KPU and CPU share 8MiB of physical memory. If KPU needs to be enabled, at least 2MiB must be reserved as the data cache of KPU, and the neural network model must be placed in the rest within 4MiB. And the Linux OS itself needs memory space, so this would be meaningless.

**Comment by JeffreyUrban** [comment]
Thanks for clarifying :)
